### ISSUE TITLE
Не понятно зачем отдельная ветка `Iuesses`

### ISSUE THREAD

**Issue by phoenixweiss** [vanilnic/homework_1#4]
Увидел что исправили, но только зачем-то создали отдельную ветку да еще и обозвали `Iuesses` вместо `Issues`. Кроме того там же еще зачем-то появился файл `script (2).js`.
Не нужно усложнять. Можете вести изменения в рамках той же самой основной ветки. Не нужно создавать отдельных файлов. Если мне понадобится посмотреть порядок изменения файлов во времени, я сам смогу переключиться на нужный коммит )

Поэтому прошу влить изменения в основную ветку, избавиться от лишнего файла и удалить лишнюю ветку.

**Comment by vanilnic** [comment]
Буквы напутала в названии, не поняла сразу, как именно нужно было исправлять. Сейчас всё сделала правильно. Надеюсь :)
